run:
  timeout: 3m
  tests: true

linters:
  enable:
    - errcheck
    - gosimple
    - staticcheck
    - ineffassign
    - revive
    - gocritic
    - govet
    - gofmt
  disable:
    - dupl
    - gocyclo

linters-settings:
  revive:
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: error-return
      - name: exported
      - name: if-return
      - name: increment-decrement
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: var-naming

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

